/**
 * Prebuild: read prompts/*.md and emit src/built-in-prompts.generated.ts
 * with each prompt as a TypeScript string literal. The generated file is
 * what src/built-in-prompts.ts imports — no .md imports in the runtime
 * path, so the compiled binary doesn't need filesystem access and pi's
 * extension loader can resolve the module.
 *
 * Run via: `bun scripts/build-prompts.ts` (called from the Makefile build
 * target before `bun build --compile`).
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const promptsDir = join(here, "..", "prompts")
const outFile = join(here, "..", "src", "built-in-prompts.generated.ts")

const files = readdirSync(promptsDir).filter((f) => f.endsWith(".md")).sort()
const entries = files.map((f) => {
  const name = f.replace(/\.md$/, "")
  const body = readFileSync(join(promptsDir, f), "utf8")
  // Escape backticks and `${` so the string is safe inside a template literal.
  const escaped = body.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")
  return `  "${name}": \`${escaped}\`,`
})

const header = `// AUTOGENERATED by scripts/build-prompts.ts — do not edit by hand.
// Re-run \`bun scripts/build-prompts.ts\` to regenerate from prompts/*.md.
export const builtInPrompts: Record<string, string> = {
`

const footer = `}
// ${entries.length} prompts: ${files.join(", ")}
`

writeFileSync(outFile, header + entries.join("\n") + "\n" + footer)
console.log(`wrote ${outFile} (${entries.length} prompts)`)
