/**
 * Built-in agent prompts. The actual prompt strings live in the
 * generated module built-in-prompts.generated.ts (regenerated by
 * `bun scripts/build-prompts.ts` before each `make build`). We re-export
 * here so call sites can keep using `./built-in-prompts`.
 *
 * This indirection is what lets the wopr-for-pi extension load cleanly:
 * there are no `.md` imports anywhere in the runtime path, so pi's
 * extension loader can resolve the module without needing to handle
 * bun's `import x from "./foo.md" with { type: "text" }` syntax.
 */
export { builtInPrompts } from "./built-in-prompts.generated"
